// Generated by tools/generate_pairwise_rank_header.py from
// rl/frozen_pairwise_rank_e105.json.  Do not edit by hand.
#pragma once

#include <array>
#include <cmath>
#include <cstddef>

namespace kag_leaf {

inline constexpr std::size_t N_LEGAL_FEATURES = 119;

enum LegalFeatureIndex : std::size_t {
    FEAT_CARRIED_TOTAL = 0,
    FEAT_DAY = 1,
    FEAT_FORWARD_ANIMAL_NEXT_YIELD_DAYS_MEAN = 2,
    FEAT_FORWARD_ANIMAL_NEXT_YIELD_DAYS_MIN = 3,
    FEAT_FORWARD_CARRIED_TO_SHED_ETA_MIN = 4,
    FEAT_FORWARD_CARRIED_TO_SHED_REACHABLE_TODAY = 5,
    FEAT_FORWARD_CARRIED_UNITS = 6,
    FEAT_FORWARD_CRITICAL_ANIMALS = 7,
    FEAT_FORWARD_CRITICAL_PLANTS = 8,
    FEAT_FORWARD_CROP_FIRST_YIELD_DAYS_MEAN = 9,
    FEAT_FORWARD_CROP_FIRST_YIELD_DAYS_MIN = 10,
    FEAT_FORWARD_DECAY_TURNS_MIN = 11,
    FEAT_FORWARD_FERTILIZED_TILES = 12,
    FEAT_FORWARD_FERTILIZER_AVAILABLE_TILES = 13,
    FEAT_FORWARD_FERTILIZER_ETA_MEAN = 14,
    FEAT_FORWARD_FERTILIZER_ETA_MIN = 15,
    FEAT_FORWARD_FERTILIZER_REACHABLE_TODAY = 16,
    FEAT_FORWARD_FERTILIZER_TARGETS = 17,
    FEAT_FORWARD_HARVEST_ETA_MEAN = 18,
    FEAT_FORWARD_HARVEST_ETA_MIN = 19,
    FEAT_FORWARD_HARVEST_REACHABLE_TODAY = 20,
    FEAT_FORWARD_HARVEST_TARGETS = 21,
    FEAT_FORWARD_PENDING_CARE_BONUS = 22,
    FEAT_FORWARD_READY_YIELD_UNITS = 23,
    FEAT_FORWARD_READY_YIELD_VALUE = 24,
    FEAT_FORWARD_SERVICE_ETA_MEAN = 25,
    FEAT_FORWARD_SERVICE_ETA_MIN = 26,
    FEAT_FORWARD_SERVICE_REACHABLE_TODAY = 27,
    FEAT_FORWARD_SERVICE_TARGETS = 28,
    FEAT_FORWARD_TERMINAL_STRANDED_OBJECTS = 29,
    FEAT_FORWARD_WEED_ETA_MEAN = 30,
    FEAT_FORWARD_WEED_ETA_MIN = 31,
    FEAT_FORWARD_WEED_REACHABLE_TODAY = 32,
    FEAT_FORWARD_WEED_TARGETS = 33,
    FEAT_HANDS = 34,
    FEAT_HOUR = 35,
    FEAT_LEGAL_MARKED_MARGIN = 36,
    FEAT_MARKET_CARROT = 37,
    FEAT_MARKET_EGG = 38,
    FEAT_MARKET_FERTILIZER = 39,
    FEAT_MARKET_MELON = 40,
    FEAT_MARKET_MILK = 41,
    FEAT_MARKET_STRAWBERRY = 42,
    FEAT_MARKET_TOMATO = 43,
    FEAT_MARKET_WHEAT = 44,
    FEAT_MARKET_WOOL = 45,
    FEAT_MONEY_DELTA = 46,
    FEAT_OPPONENT_ANIMAL_COW = 47,
    FEAT_OPPONENT_ANIMAL_GOOSE = 48,
    FEAT_OPPONENT_ANIMAL_SHEEP = 49,
    FEAT_OPPONENT_ANIMALS_UNFED = 50,
    FEAT_OPPONENT_CROP_CARROT = 51,
    FEAT_OPPONENT_CROP_MELON = 52,
    FEAT_OPPONENT_CROP_STRAWBERRY = 53,
    FEAT_OPPONENT_CROP_TOMATO = 54,
    FEAT_OPPONENT_CROP_WHEAT = 55,
    FEAT_OPPONENT_HANDS = 56,
    FEAT_OPPONENT_HIRES_TODAY = 57,
    FEAT_OPPONENT_MONEY = 58,
    FEAT_OPPONENT_PLANTS_UNWATERED = 59,
    FEAT_OPPONENT_PUBLIC_MARKED_VALUE = 60,
    FEAT_OPPONENT_TILE_COOP = 61,
    FEAT_OPPONENT_TILE_PASTURE = 62,
    FEAT_OPPONENT_TILE_PLANT = 63,
    FEAT_OPPONENT_TILE_WEED = 64,
    FEAT_OPPONENT_TILES_WITH_YIELD = 65,
    FEAT_OPPONENT_UNLOCKED = 66,
    FEAT_OWN_ANIMAL_COW = 67,
    FEAT_OWN_ANIMAL_GOOSE = 68,
    FEAT_OWN_ANIMAL_SHEEP = 69,
    FEAT_OWN_ANIMALS_UNFED = 70,
    FEAT_OWN_CROP_CARROT = 71,
    FEAT_OWN_CROP_MELON = 72,
    FEAT_OWN_CROP_STRAWBERRY = 73,
    FEAT_OWN_CROP_TOMATO = 74,
    FEAT_OWN_CROP_WHEAT = 75,
    FEAT_OWN_HIRES_TODAY = 76,
    FEAT_OWN_MONEY = 77,
    FEAT_OWN_PLANTS_UNWATERED = 78,
    FEAT_OWN_PRIVATE_MARKED_VALUE = 79,
    FEAT_OWN_TILE_COOP = 80,
    FEAT_OWN_TILE_PASTURE = 81,
    FEAT_OWN_TILE_PLANT = 82,
    FEAT_OWN_TILE_WEED = 83,
    FEAT_OWN_TILES_WITH_YIELD = 84,
    FEAT_PRICE_CARROT = 85,
    FEAT_PRICE_EGG = 86,
    FEAT_PRICE_FERTILIZER = 87,
    FEAT_PRICE_MELON = 88,
    FEAT_PRICE_MILK = 89,
    FEAT_PRICE_STRAWBERRY = 90,
    FEAT_PRICE_TOMATO = 91,
    FEAT_PRICE_WHEAT = 92,
    FEAT_PRICE_WOOL = 93,
    FEAT_SEED_CARROT = 94,
    FEAT_SEED_MELON = 95,
    FEAT_SEED_STRAWBERRY = 96,
    FEAT_SEED_TOMATO = 97,
    FEAT_SEED_WHEAT = 98,
    FEAT_SHED_CARROT = 99,
    FEAT_SHED_EGG = 100,
    FEAT_SHED_FERTILIZER = 101,
    FEAT_SHED_MELON = 102,
    FEAT_SHED_MILK = 103,
    FEAT_SHED_STRAWBERRY = 104,
    FEAT_SHED_TOMATO = 105,
    FEAT_SHED_TOTAL = 106,
    FEAT_SHED_WHEAT = 107,
    FEAT_SHED_WOOL = 108,
    FEAT_SHOP_BAKERY = 109,
    FEAT_SHOP_BRUNCH_SPOT = 110,
    FEAT_SHOP_FARMERS_MARKET = 111,
    FEAT_SHOP_ICE_CREAM_SHOP = 112,
    FEAT_SHOP_PET_CAFE = 113,
    FEAT_SHOP_PIZZA_SHOP = 114,
    FEAT_SHOP_SMOOTHIE_SHOP = 115,
    FEAT_SHOP_YARN_STORE = 116,
    FEAT_STEP = 117,
    FEAT_UNLOCKED = 118
};

using LegalFeatureVector = std::array<double, N_LEGAL_FEATURES>;

inline constexpr std::array<const char*, N_LEGAL_FEATURES> LEGAL_FEATURE_NAMES = {{
    "carried_total",
    "day",
    "forward_animal_next_yield_days_mean",
    "forward_animal_next_yield_days_min",
    "forward_carried_to_shed_eta_min",
    "forward_carried_to_shed_reachable_today",
    "forward_carried_units",
    "forward_critical_animals",
    "forward_critical_plants",
    "forward_crop_first_yield_days_mean",
    "forward_crop_first_yield_days_min",
    "forward_decay_turns_min",
    "forward_fertilized_tiles",
    "forward_fertilizer_available_tiles",
    "forward_fertilizer_eta_mean",
    "forward_fertilizer_eta_min",
    "forward_fertilizer_reachable_today",
    "forward_fertilizer_targets",
    "forward_harvest_eta_mean",
    "forward_harvest_eta_min",
    "forward_harvest_reachable_today",
    "forward_harvest_targets",
    "forward_pending_care_bonus",
    "forward_ready_yield_units",
    "forward_ready_yield_value",
    "forward_service_eta_mean",
    "forward_service_eta_min",
    "forward_service_reachable_today",
    "forward_service_targets",
    "forward_terminal_stranded_objects",
    "forward_weed_eta_mean",
    "forward_weed_eta_min",
    "forward_weed_reachable_today",
    "forward_weed_targets",
    "hands",
    "hour",
    "legal_marked_margin",
    "market_carrot",
    "market_egg",
    "market_fertilizer",
    "market_melon",
    "market_milk",
    "market_strawberry",
    "market_tomato",
    "market_wheat",
    "market_wool",
    "money_delta",
    "opponent_animal_cow",
    "opponent_animal_goose",
    "opponent_animal_sheep",
    "opponent_animals_unfed",
    "opponent_crop_carrot",
    "opponent_crop_melon",
    "opponent_crop_strawberry",
    "opponent_crop_tomato",
    "opponent_crop_wheat",
    "opponent_hands",
    "opponent_hires_today",
    "opponent_money",
    "opponent_plants_unwatered",
    "opponent_public_marked_value",
    "opponent_tile_coop",
    "opponent_tile_pasture",
    "opponent_tile_plant",
    "opponent_tile_weed",
    "opponent_tiles_with_yield",
    "opponent_unlocked",
    "own_animal_cow",
    "own_animal_goose",
    "own_animal_sheep",
    "own_animals_unfed",
    "own_crop_carrot",
    "own_crop_melon",
    "own_crop_strawberry",
    "own_crop_tomato",
    "own_crop_wheat",
    "own_hires_today",
    "own_money",
    "own_plants_unwatered",
    "own_private_marked_value",
    "own_tile_coop",
    "own_tile_pasture",
    "own_tile_plant",
    "own_tile_weed",
    "own_tiles_with_yield",
    "price_carrot",
    "price_egg",
    "price_fertilizer",
    "price_melon",
    "price_milk",
    "price_strawberry",
    "price_tomato",
    "price_wheat",
    "price_wool",
    "seed_carrot",
    "seed_melon",
    "seed_strawberry",
    "seed_tomato",
    "seed_wheat",
    "shed_carrot",
    "shed_egg",
    "shed_fertilizer",
    "shed_melon",
    "shed_milk",
    "shed_strawberry",
    "shed_tomato",
    "shed_total",
    "shed_wheat",
    "shed_wool",
    "shop_bakery",
    "shop_brunch_spot",
    "shop_farmers_market",
    "shop_ice_cream_shop",
    "shop_pet_cafe",
    "shop_pizza_shop",
    "shop_smoothie_shop",
    "shop_yarn_store",
    "step",
    "unlocked"
}};

struct PairwisePhase {
    const char* name;
    int start;
    int stop;
    double margin_threshold;
    double confidence_threshold;
    double intercept;
    LegalFeatureVector weights;
};

inline constexpr std::array<PairwisePhase, 4> FROZEN_PAIRWISE_PHASES = {{
    PairwisePhase{
        "early", 24, 192,
        2000, 0.0, -6.8843060791992635e-18,
        LegalFeatureVector{{
            0.0, 0.0, 0.28219888365111923, 0.64611290939358268, 0.0, 0.0,
            0.0, 0.030608534883825103, -0.02842258287790202, 0.0097594971518703156, 0.1659267782937765, -0.0052547076071210088,
            0.36385284361681686, -0.028050252060641233, -1.297090319400044, 0.0, -0.028050252060641961, -0.028050252060642863,
            -0.0071476687612018613, -0.0033165748722353457, -0.010798585345004771, -0.010798585345005078, 0.010732545997399983, 0.011480286090447621,
            -0.00042454077312604371, -1.0934807182815407, 0.0, 0.011835806774178045, 0.011835806774177952, 0.0,
            0.05941352788819064, 0.0313738533479163, -0.19804833959187287, -0.19804833959187326, 0.0, 0.0,
            -1.4768358797414077e-05, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, -1.0585831779889878e-05, 0.087372920508463958,
            -0.097620814574640197, -0.080486249495944767, 0.028050252060638343, -0.093466459815661596, 0.0051090274092414813, -0.022723148051750731,
            -0.12548107918593482, -0.0018474558695040502, 0.0, 0.0, 2.1171663559775904e-05, -0.010916070473622254,
            2.143303040608369e-05, 0.19712996391729753, -0.00044813106855826887, -0.010916070473622048, 0.19804833959186349, 0.0050230187968319179,
            0.62065410479122729, -0.087372920508462432, 0.097620814574631523, 0.080486249495943671, -0.02805025206063869, 0.093466459815661623,
            -0.0051090274092414232, 0.022723148051750297, 0.12548107918593299, 0.001847455869503909, 0.0, -2.1171663559774647e-05,
            0.010916070473622173, -0.00060380643771310277, -0.19712996391729712, 0.00044813106855839225, 0.010916070473622171, -0.19804833959186308,
            -0.0050230187968320888, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, -0.020372136995742966, -0.052072711727151347,
            0.1076310120585157, 0.0, -0.013794435318599262, 0.057743752463562954, 0.0, 0.03145037629621121,
            0.0, 0.0, 0.0, 0.0, -8.1917868206864822e-05, -0.0010008964235441475,
            0.16330691497445129, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, -0.62065410479124572
        }}
    },
    PairwisePhase{
        "mid", 216, 480,
        16000, 0.20000000000000001, -1.679625958770162e-18,
        LegalFeatureVector{{
            0.0, 0.0, 0.070960270655598526, 0.13507443659590593, 0.0, 0.0,
            0.0, -0.0039658742049545614, -0.011126459661652733, -0.044396810420302767, 0.10192554886096163, 0.0010385710283421939,
            0.0092444219362808507, -0.004001372208822138, -0.15410003730588354, 0.0, -0.004001372208822138, -0.0040013722088221345,
            0.027819390837375158, -0.0013255846168241843, 0.001762356279681541, 0.0017623562796815363, 0.0017311325748227675, -0.00017627295938182056,
            2.5931605073031366e-06, -0.13279818286932663, 0.0, 0.0016259650042422526, 0.0016259650042422516, 0.0,
            -0.0077704168025982262, -0.0077121765972957453, -0.0087219277568906187, -0.0087219277568906361, 0.0, 0.0,
            5.3780264602037977e-06, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 1.0371133141327199e-06, -0.01161372139236585,
            0.010970991329947315, 0.015499298909582277, 0.0040013722088221423, 0.020920162913304414, 0.0089967060115691867, -0.0028898901188160646,
            -0.015117246339260952, -0.0029650482222156964, 0.0, 0.0, -2.0742266282654415e-06, -0.0017760493381290706,
            -9.0635100101062326e-06, 0.015264058813214599, -0.0048243046239040922, -0.0017760493381290719, 0.0087219277568906326, 0.0022678362142456426,
            -0.077655038000100568, 0.01161372139236585, -0.010970991329947322, -0.015499298909582255, -0.004001372208822144, -0.0209201629133044,
            -0.0089967060115691763, 0.0028898901188160638, 0.015117246339260948, 0.0029650482222156943, 0.0, 2.0742266282654398e-06,
            0.0017760493381290725, 7.0791686686916416e-06, -0.015264058813214576, 0.0048243046239040896, 0.0017760493381290725, -0.0087219277568906291,
            -0.0022678362142456413, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, -0.007326864399321756, -0.1926929500584425,
            -0.008063470292340464, 0.016187923045944304, -0.0054112652484445854, -0.0028522139702960789, -0.0047965011494409803, 0.0029677996820822406,
            -0.00022368962287528985, -0.0098198118857375678, 0.0095964937876357927, 0.0049984486558501502, 6.7968363487466536e-05, -0.00061227197427031325,
            7.5370207029587408e-05, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 0.077655038000100624
        }}
    },
    PairwisePhase{
        "late", 504, 576,
        8000, 0.40000000000000002, -1.0376011010618099e-17,
        LegalFeatureVector{{
            0.0, 0.0, 0.25110829155233205, -0.06573994436772905, 0.0, 0.0,
            0.0, -0.0050301460891799508, -0.0071373951725626304, 0.39206043940712071, 0.0, 0.00036455759534041645,
            0.0021330274096135371, 0.0026787165332195053, -0.099439568174514506, 0.25784173684911393, 0.0026787165332195126, 0.0026787165332195001,
            0.033533242271109188, 0.040637635458436357, 0.0040108211475262416, 0.0040108211475262442, 0.021601359956086551, 0.00065853206985744446,
            -2.7502590226843357e-06, -0.32274728598514152, 0.25784173684911416, 0.0030469237979260408, 0.0030469237979260386, 0.0,
            0.016367015667754687, 0.014101485997178731, -0.0017731971453754363, -0.0017731971453754372, 0.0, 0.0,
            1.5287044741124191e-05, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 1.3480671129750086e-05, -0.012747407575584329,
            -0.013722038614552727, 0.012541730836105332, -0.0026787165332195348, 0.011594646584505241, 0.0016822325065694479, -2.5258958481225985e-05,
            -0.010597006027043214, -0.00080572562925675757, 0.0, 0.0, -2.6961342259500145e-05, -0.0025878468496135379,
            -2.2197424115881308e-05, -0.020568871281823435, 0.022698513840069958, -0.0025878468496135453, 0.0017731971453754144, -0.00063251681642753676,
            -0.19428364192384481, 0.012747407575584376, 0.013722038614552715, -0.012541730836105354, 0.0026787165332195348, -0.011594646584505255,
            -0.001682232506569457, 2.5258958481226395e-05, 0.010597006027043165, 0.00080572562925675334, 0.0, 2.6961342259500135e-05,
            0.0025878468496135332, 0.00010461135274035916, 0.02056887128182347, -0.022698513840069934, 0.0025878468496135323, -0.0017731971453754047,
            0.00063251681642753686, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 0.013177943474252468, -0.25677823478372425,
            -0.058289932447001445, 0.069466560375828795, 0.0025652626912417765, 0.0015070516450279466, 0.00067879359356737561, -0.006290432509524534,
            0.0081319889188660836, 0.0070936649396974973, 0.0049051526403613701, -0.0063888969277401501, 0.0033348259141793134, 0.00611610660497665,
            -0.019509591713614823, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 0.19428364192384492
        }}
    },
    PairwisePhase{
        "terminal", 600, 648,
        8000, 0.80000000000000004, 3.1869217063567542e-17,
        LegalFeatureVector{{
            0.0, 0.0, 0.11898053652324146, -1.5561804701959916, 0.0, 0.0,
            0.0, -0.038608558944787132, 0.0050065761680248332, 0.99790564323321707, 0.0, -0.0033037517447488608,
            -0.0080701885797783111, 0.070121068045182713, -0.18469852080381371, -1.5561804701958679, 0.070121068045203391, 0.070121068045203391,
            -0.086918179737712653, 0.14248372187986061, 0.021510773523402221, 0.02151077352340288, -0.0021727777805613112, 0.0039330930385423494,
            4.1105990057892e-05, -0.1666146779396874, 0.77809023509789044, 0.0062196000432476412, 0.0062196000432459932, 0.14168090798820929,
            -0.079115555853804448, 0.096371863259694171, 0.002639331073054967, 0.0026393310730552593, 0.0, 0.0,
            2.5321985193715508e-05, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 2.0264164781032543e-05, -0.11281192582536882,
            0.13925694628561938, -0.051187372283369059, -0.070121068045185364, -0.015085551208161468, 0.0, 0.015445239626190656,
            -0.040287994294839258, -0.00056695470345134377, 0.0, 0.0, -4.052832956206537e-05, -0.00056268712155738024,
            -1.9585330948199959e-05, 0.016943988767827042, 0.36713563523650866, -0.00056268712155820087, -0.0026393310730538654, 0.028547052269171293,
            -0.25433230989942635, 0.11281192582536798, -0.13925694628561641, 0.051187372283406654, 0.070121068045182172, 0.015085551208162223,
            0.0, -0.015445239626191133, 0.040287994294835344, 0.00056695470345176, 0.0, 4.0528329562063249e-05,
            0.00056268712155730239, 0.00021271107988906092, -0.016943988767827073, -0.36713563523654241, 0.00056268712155729784, 0.0026393310730538637,
            -0.02854705226917028, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 0.0010187867222534929, -0.22559625918809637,
            -0.057239356635877217, 0.2487205067306387, 0.03811564641828085, -0.0028602398276170934, -0.0297927716006198, -0.003540884328533386,
            0.2472752267728833, 0.012138864276370089, 0.001530154580139493, 0.047185557739314751, 0.0018075302659395346, 0.0010075905644780106,
            0.0077610226125057894, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 0.25433230989940797
        }}
    }
}};

inline const PairwisePhase* pairwise_phase_for_step(int step) {
    for (const PairwisePhase& phase : FROZEN_PAIRWISE_PHASES)
        if (phase.start <= step && step <= phase.stop) return &phase;
    return nullptr;
}

inline double scalar_rank_score(
    const LegalFeatureVector& features,
    const PairwisePhase& phase
) {
    double score = 0.0;
    for (std::size_t index = 0; index < N_LEGAL_FEATURES; ++index)
        score += features[index] * phase.weights[index];
    return score;
}

inline double learned_pairwise_score(
    const LegalFeatureVector& left,
    const LegalFeatureVector& right,
    const PairwisePhase& phase
) {
    return phase.intercept + scalar_rank_score(left, phase)
         - scalar_rank_score(right, phase);
}

inline int confidence_compare(
    double current_margin_difference,
    double learned_score,
    const PairwisePhase& phase,
    bool* overridden = nullptr
) {
    const int current_sign = (current_margin_difference > 0.0)
        - (current_margin_difference < 0.0);
    const int learned_sign = (learned_score > 0.0) - (learned_score < 0.0);
    const bool eligible =
        std::abs(current_margin_difference) <= phase.margin_threshold &&
        std::abs(learned_score) >= phase.confidence_threshold &&
        learned_sign != 0;
    const bool use_learned = eligible && learned_sign != current_sign;
    if (overridden) *overridden = use_learned;
    return use_learned ? learned_sign : current_sign;
}

}  // namespace kag_leaf
