"""Generate the native frozen N75 rank model from its tracked JSON artifact.

The generated header keeps the exact sorted feature order used by Python and
folds ridge centering/scaling into one raw coefficient per legal leaf feature.
It is deterministic: rerunning it on the same JSON must produce a byte-identical
header, which lets tests detect stale or hand-edited native weights.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def identifier(name: str) -> str:
    value = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_").upper()
    if not value or value[0].isdigit():
        value = "X_" + value
    return "FEAT_" + value


def number(value: float) -> str:
    value = float(value)
    if value == 0.0:
        return "0.0"
    return format(value, ".17g")


def collapsed_ridge(rank: dict, feature_count: int) -> tuple[float, list[float]]:
    """Return intercept/raw weights equivalent to serialized_ridge_predict."""

    ridge = rank["ridge"]
    center = list(map(float, ridge["center"]))
    scale = list(map(float, ridge["scale"]))
    active = list(map(int, ridge["active_indices"]))
    fitted = list(map(float, ridge["weights"]))
    if len(center) != feature_count or len(scale) != feature_count:
        raise ValueError("feature width mismatch")
    if len(active) != len(fitted):
        raise ValueError("active/weight width mismatch")
    raw = [0.0] * feature_count
    intercept = float(ridge["target_center"])
    for index, weight in zip(active, fitted):
        if scale[index] == 0.0:
            raise ValueError(f"zero scale at {index}")
        raw[index] = weight / scale[index]
        intercept -= center[index] * raw[index]
    return intercept, raw


def phase_row(name: str, phase: dict, feature_count: int) -> str:
    rank = phase["rank"]
    if rank["kind"] != "confidence_ridge":
        raise ValueError(f"unsupported rank kind in {name}: {rank['kind']}")
    try:
        intercept, raw = collapsed_ridge(rank, feature_count)
    except ValueError as error:
        raise ValueError(f"{name}: {error}") from error
    weight_lines = []
    for start in range(0, feature_count, 6):
        values = ", ".join(number(value) for value in raw[start : start + 6])
        weight_lines.append("            " + values)
    weights = ",\n".join(weight_lines)
    return (
        "    PairwisePhase{\n"
        f"        \"{name}\", {int(phase['start'])}, {int(phase['stop'])},\n"
        f"        {number(rank['margin_threshold'])}, "
        f"{number(rank['confidence_threshold'])}, {number(intercept)},\n"
        "        LegalFeatureVector{{\n"
        f"{weights}\n"
        "        }}\n"
        "    }"
    )


def render(model: dict, source: Path) -> str:
    if model.get("schema") != "kaggriculture-pairwise-leaf-rank-v1":
        raise ValueError("unexpected model schema")
    names = list(map(str, model["feature_names"]))
    if names != sorted(names) or len(names) != len(set(names)):
        raise ValueError("feature names must be unique and sorted")
    enum_rows = ",\n".join(
        f"    {identifier(name)} = {index}" for index, name in enumerate(names)
    )
    name_rows = ",\n".join(f'    "{name}"' for name in names)
    phase_rows = ",\n".join(
        phase_row(name, phase, len(names))
        for name, phase in model["phases"].items()
    )
    return f"""// Generated by tools/generate_pairwise_rank_header.py from
// {source.as_posix()}.  Do not edit by hand.
#pragma once

#include <array>
#include <cmath>
#include <cstddef>

namespace kag_leaf {{

inline constexpr std::size_t N_LEGAL_FEATURES = {len(names)};

enum LegalFeatureIndex : std::size_t {{
{enum_rows}
}};

using LegalFeatureVector = std::array<double, N_LEGAL_FEATURES>;

inline constexpr std::array<const char*, N_LEGAL_FEATURES> LEGAL_FEATURE_NAMES = {{{{
{name_rows}
}}}};

struct PairwisePhase {{
    const char* name;
    int start;
    int stop;
    double margin_threshold;
    double confidence_threshold;
    double intercept;
    LegalFeatureVector weights;
}};

inline constexpr std::array<PairwisePhase, {len(model['phases'])}> FROZEN_PAIRWISE_PHASES = {{{{
{phase_rows}
}}}};

inline const PairwisePhase* pairwise_phase_for_step(int step) {{
    for (const PairwisePhase& phase : FROZEN_PAIRWISE_PHASES)
        if (phase.start <= step && step <= phase.stop) return &phase;
    return nullptr;
}}

inline double scalar_rank_score(
    const LegalFeatureVector& features,
    const PairwisePhase& phase
) {{
    double score = 0.0;
    for (std::size_t index = 0; index < N_LEGAL_FEATURES; ++index)
        score += features[index] * phase.weights[index];
    return score;
}}

inline double learned_pairwise_score(
    const LegalFeatureVector& left,
    const LegalFeatureVector& right,
    const PairwisePhase& phase
) {{
    return phase.intercept + scalar_rank_score(left, phase)
         - scalar_rank_score(right, phase);
}}

inline int confidence_compare(
    double current_margin_difference,
    double learned_score,
    const PairwisePhase& phase,
    bool* overridden = nullptr
) {{
    const int current_sign = (current_margin_difference > 0.0)
        - (current_margin_difference < 0.0);
    const int learned_sign = (learned_score > 0.0) - (learned_score < 0.0);
    const bool eligible =
        std::abs(current_margin_difference) <= phase.margin_threshold &&
        std::abs(learned_score) >= phase.confidence_threshold &&
        learned_sign != 0;
    const bool use_learned = eligible && learned_sign != current_sign;
    if (overridden) *overridden = use_learned;
    return use_learned ? learned_sign : current_sign;
}}

}}  // namespace kag_leaf
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("model", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    model = json.loads(args.model.read_text(encoding="utf-8"))
    rendered = render(model, args.model)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
