"""Generate the native frozen N74 final-margin value head."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

try:
    from tools.generate_pairwise_rank_header import collapsed_ridge, number
except ModuleNotFoundError:
    from generate_pairwise_rank_header import collapsed_ridge, number  # type: ignore


def phase_row(name: str, phase: dict, feature_count: int) -> str:
    regression = phase["targets"]["final_margin"]
    if regression["kind"] != "ridge_blend":
        raise ValueError(f"{name}: unsupported kind {regression['kind']}")
    if regression["offset"] != "legal_marked":
        raise ValueError(f"{name}: unsupported offset {regression['offset']}")
    if regression["fallback"] not in {"zero", "current_money"}:
        raise ValueError(f"{name}: unsupported fallback {regression['fallback']}")
    intercept, raw = collapsed_ridge(regression, feature_count)
    weight_lines = []
    for start in range(0, feature_count, 6):
        values = ", ".join(number(value) for value in raw[start : start + 6])
        weight_lines.append("            " + values)
    weights = ",\n".join(weight_lines)
    return (
        "    FinalValuePhase{\n"
        f"        \"{name}\", {int(phase['start'])}, {int(phase['stop'])}, "
        f"{'true' if regression['fallback'] == 'current_money' else 'false'},\n"
        f"        {number(regression['blend'])}, {number(intercept)},\n"
        "        LegalFeatureVector{{\n"
        f"{weights}\n"
        "        }}\n"
        "    }"
    )


def render(model: dict, source: Path) -> str:
    if model.get("schema") != "kaggriculture-phase-leaf-value-v1":
        raise ValueError("unexpected phase model schema")
    names = list(map(str, model["feature_names"]))
    phases = ",\n".join(
        phase_row(name, phase, len(names))
        for name, phase in model["phases"].items()
    )
    return f"""// Generated by tools/generate_phase_value_header.py from
// {source.as_posix()}.  Do not edit by hand.
#pragma once

#include "frozen_pairwise_rank_e105.hpp"

#include <array>

namespace kag_leaf {{

struct FinalValuePhase {{
    const char* name;
    int start;
    int stop;
    bool fallback_current_money;
    double blend;
    double intercept;
    LegalFeatureVector weights;
}};

inline constexpr std::array<FinalValuePhase, {len(model['phases'])}> FROZEN_FINAL_VALUE_PHASES = {{{{
{phases}
}}}};

inline const FinalValuePhase* final_value_phase_for_step(int step) {{
    for (const FinalValuePhase& phase : FROZEN_FINAL_VALUE_PHASES)
        if (phase.start <= step && step <= phase.stop) return &phase;
    return nullptr;
}}

inline double frozen_final_margin_value(
    const LegalFeatureVector& features,
    const FinalValuePhase& phase
) {{
    double residual = phase.intercept;
    for (std::size_t index = 0; index < N_LEGAL_FEATURES; ++index)
        residual += features[index] * phase.weights[index];
    const double raw = features[FEAT_LEGAL_MARKED_MARGIN] + residual;
    const double fallback = phase.fallback_current_money
        ? features[FEAT_MONEY_DELTA]
        : 0.0;
    return fallback + phase.blend * (raw - fallback);
}}

}}  // namespace kag_leaf
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("model", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    model = json.loads(args.model.read_text(encoding="utf-8"))
    rendered = render(model, args.model)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
